name: CI/CD Pipeline

on:
  push:
    branches:
      - master       # Produção
      - staging      # Estágio
      - develop      # Desenvolvimento
  pull_request:
    branches:
      - master
      - staging
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Montar o projeto
        run: |
          echo "Executando montagem do projeto"
          go build ./...

  review:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Review Environment
        run: |
          echo "Deploying to Review Environment"
          # Adicione seu script para criar um ambiente temporário de revisão aqui
          # Por exemplo, comandos Docker ou Kubernetes para criar um ambiente isolado.

  staging:
    runs-on: ubuntu-latest
    needs: review
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment"
          # Adicione seu script para implantar no ambiente de staging aqui

  dast:
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start OWASP ZAP
        run: |
          echo "Iniciando OWASP ZAP para testes DAST"
          docker run -u zap -p 8081:8081 -v /home/aluno/Downloads/ZAP_D-2024-09-17:/home/zap/.ZAP --rm owasp/zap2docker-stable zap.sh -daemon -port 8081 -host 0.0.0.0 -config api.disablekey=true -quickurl http://staging-url -quickprogress
          # Substitua http://staging-url pelo URL real do ambiente de staging

      - name: Run OWASP ZAP DAST Scan
        run: |
          echo "Executando testes de segurança com OWASP ZAP"
          # Comando para executar a varredura e gerar relatórios
          docker run -u zap --network="host" --rm owasp/zap2docker-stable zap.sh -cmd -quickurl http://staging-url -quickout /home/zap/.ZAP/zap-report.html -reportformat html
          # Certifique-se de que o diretório está montado corretamente.

      - name: Upload DAST Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: /home/aluno/Downloads/ZAP_D-2024-09-17/zap-report.html # Substitua pelo caminho do relatório do ZAP