name: CI Pipeline

on:
  push:
    branches:
      - master       # Produção
      - staging      # Estágio
      - develop      # Desenvolvimento
  pull_request:
    branches:
      - master
      - staging
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        env:
          DOCKER_BUILDKIT: 1  # Habilita o BuildKit
        run: |
          echo "Iniciando a compilação do código"
          docker build -t ex-build-dev:latest .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Run Tests
        run: |
          echo "Executando testes automatizados"
          mkdir -p coverage 
          go test -v -coverprofile=coverage.out -covermode=set ./...
          pwd 
          ls -la coverage 
          cat coverage.out